# Generated by Django 4.2.4 on 2023-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideas',
            old_name='code',
            new_name='idea',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='title',
        ),
        migrations.AddField(
            model_name='ideas',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
